---
version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.0
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:3.2.0
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_NUM_PARTITIONS: 18

  jobmanager1:
    image: qb-flink
    build: ./qb-flink
    container_name: jobmanager1
    hostname: jobmanager1
    depends_on:
      - zookeeper
    expose:
      - "6123"
    ports:
      - "48081:8081"
    command: jobmanager
    volumes:
      - state:/var/qb/state
      - recovery:/var/qb/recovery

  jobmanager2:
    image: qb-flink
    build: ./qb-flink
    container_name: jobmanager2
    hostname: jobmanager2
    depends_on:
      - zookeeper
    expose:
      - "6123"
    ports:
      - "58081:8081"
    command: jobmanager
    volumes:
      - state:/var/qb/state
      - recovery:/var/qb/recovery

  taskmanager1:
    image: qb-flink
    build: ./qb-job/build
    container_name: taskmanager1
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager1
      - zookeeper
    command: taskmanager
    volumes:
      - state:/var/qb/state
      - ./build/invoices:/var/qb/invoices

  taskmanager2:
    image: qb-flink
    build: ./qb-job/build
    container_name: taskmanager2
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager1
      - zookeeper
    command: taskmanager
    volumes:
      - state:/var/qb/state
      - ./build/invoices:/var/qb/invoices

  qb-job:
    image: qb-job:0.1-SNAPSHOT
    build: ./qb-job/build
    container_name: qb-job
    depends_on:
      - jobmanager1
      - kafka
    command: flink run -p 6 qb-job-0.1-SNAPSHOT-all.jar --output /var/qb/invoices --bootstrap-servers kafka:9092

  qb-data-generator:
    image: qb-data-generator:0.1-SNAPSHOT
    build: ./qb-data-generator/build
    container_name: qb-data-generator
    depends_on:
      - kafka
      - qb-job
    command: java -jar qb-data-generator-0.1-SNAPSHOT-all.jar kafka:9092

  qb-server:
    image: qb-server:0.1-SNAPSHOT
    build: ./qb-server/build
    container_name: qb-server
    ports:
       - "8080:8080"
    depends_on:
       - qb-job

  qb-frontend:
    image: qb-frontend
    build: ./qb-frontend
    container_name: qb-frontend
    ports:
       - "8088:80"
    depends_on:
       - qb-server

volumes:
  state:
  recovery:
