---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker1:
    image: confluentinc/cp-kafka:3.2.0
    hostname: broker1
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker1:9092'

  jobmanager:
    image: flink
    container_name: "jobmanager"
    expose:
      - "6123"
    ports:
      - "48081:8081"
    networks:
      appnetwork:
        ipv4_address: "172.16.238.11"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS="jobmanager"

  taskmanager1:
    image: flink
    expose:
      - "6121"
      - "6122"
    networks:
      appnetwork:
        ipv4_address: "172.16.238.12"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS="jobmanager"

networks:
  appnetwork:
    ipam:
      driver:
        default
      config:
      - subnet: "172.16.238.0/24"
        gateway: "172.16.238.1"
