---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.0
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker1:
    image: confluentinc/cp-kafka:3.2.0
    container_name: broker1
    hostname: broker1
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker1:9092'

  jobmanager:
    image: flink
    container_name: jobmanager
    hostname: jobmanager
    expose:
      - "6123"
    ports:
      - "48081:8081"
    command: jobmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: 'jobmanager'

  taskmanager1:
    image: qb-job:0.1-SNAPSHOT
    container_name: taskmanager1
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./build/invoices:/var/qb/invoices
    environment:
      JOB_MANAGER_RPC_ADDRESS: 'jobmanager'

  qb-job:
    image: qb-job:0.1-SNAPSHOT
    container_name: qb-job
    depends_on:
      - jobmanager
      - broker1
    command: flink run --jobmanager jobmanager:6123 qb-job-0.1-SNAPSHOT-all.jar --output /var/qb/invoices --bootstrap-servers broker1:9092

  qb-data-generator:
    image: qb-data-generator:0.1-SNAPSHOT
    container_name: qb-data-generator
    depends_on:
      - broker1
    command: java -jar qb-data-generator-0.1-SNAPSHOT-all.jar broker1:9092


  qb-server:
    image: qb-server:0.1-SNAPSHOT
    container_name: qb-server
    ports:
       - "8080:8080"
    depends_on:
       - qb-job